### ISSUE TITLE
Collaboration not working inside file but works in terminal.

### ISSUE THREAD

**Issue by vanyle** [jupyterlab/jupyter-collaboration#253]
## Description

While I can see cursors and selections of other people, the file is not saved automatically and I cannot see what other users are typing. I does not work for notebooks or plain text files.
When using a terminal however, collaboration works properly.

![image](https://github.com/jupyterlab/jupyter-collaboration/assets/9964043/a59c1bbf-1f98-47fe-8355-eeefbcfadada)

## Reproduce

I'm using the following `docker-compose.yml` file:

```yaml
services:
  jupyter:
    image:  jupyter/pyspark-notebook:latest
    restart: unless-stopped
    ports:
      - "8888:8888"
    user: root
    working_dir: /home/vanyle
    environment:
      - NB_USER=vanyle
      - CHOWN_HOME=yes
    command: "start-notebook.py --ServerApp.token='' --ServerApp.password=''"
    volumes:
      - ./models:/home/vanyle/work
```
When the docker is started, I manually install `jupyter_collaboration` and I restart the docker.

## Expected behavior

I would expect *jupyter-collaboration* to work. When a character is typed on one device, it appears on the other.

## Context

- Operating System: The issue occurs on all OS I tested, including Windows 11 and MacOS (meaning the docker is executed inside MacOS / inside Windows).
- Browser and version: The issue arises on all browser I tested, including Firefox, Edge and Chrome.
- JupyterLab version: 4.1.4
- Jupyter collaboration version: 2.0.3

I have the following plugins installed:

![image](https://github.com/jupyterlab/jupyter-collaboration/assets/9964043/51a6b62f-98c8-4bdb-abc5-f5f150669f64)
