### ISSUE TITLE
Translations are not loaded in the share dialog

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyter-collaboration#487]
![Image](https://github.com/user-attachments/assets/3c280550-c3ec-4561-ab0c-e9bfadcf7ef5)

Noticed when reviewing #438 

https://github.com/jupyterlab/jupyter-collaboration/blob/7a3986a5be99e258497cc4b51a7755824137b107/packages/collaboration/src/sharedlink.ts#L112

vs

https://github.com/jupyterlab/jupyter-collaboration/blob/7a3986a5be99e258497cc4b51a7755824137b107/packages/docprovider-extension/src/filebrowser.ts#L65

vs

https://github.com/jupyterlab/jupyter-collaboration/blob/7a3986a5be99e258497cc4b51a7755824137b107/packages/docprovider/src/notebookCellExecutor.ts#L46

vs

https://github.com/jupyterlab/jupyter-collaboration/blob/7a3986a5be99e258497cc4b51a7755824137b107/packages/collaboration-extension/src/collaboration.ts#L143

**Comment by Hyrla** [comment]
@krassowski how do you think we should handle the documentation of this feature? Especially regarding the permissions needed to make it working. On my Hub, I've simply added this to my Z2JH yaml config:

```
hub:
[...]
  loadRoles:
    share:
      description: Allow users to manage shares on their server
      scopes: [shares!user, read:users:name, list:users, servers!user]
      groups: [d35c2143-xxxx, 6bdd8535-xxxx, c481a9cf-xxxx, c1927c2a-xxxx, ba715d4d-xxxx, 6c7c5e80-xxxx, 9e98f201-xxxx, 4e3c0034-xxxx]
```

Then I've added this extra config to give these permissions to the lab's scope:

```
hub:
[...]
 extraConfig:
  customLabScopesOptions: |
      c.Spawner.oauth_client_allowed_scopes = ["read:users:name", "shares!user", "list:users", "servers!user"]
```

Finally, I've added this extra config to remove the oauth confirmation page (which I found not necessary for my use case):
```
hub:
[...]
 extraConfig:
 [...]
    disableConfirmation: |
      # Désactivation de la page de confirmation relou
      import jupyterhub.apihandlers.auth
      class DisableConfirmationOAuthAuthorizeHandler(
          jupyterhub.apihandlers.auth.OAuthAuthorizeHandler
      ):
          def needs_oauth_confirm(self, *args, **kwargs):
              return False
      for i, (route, handler) in enumerate(jupyterhub.apihandlers.default_handlers):
          if route == "/api/oauth2/authorize":
              jupyterhub.apihandlers.default_handlers[i] = (route, DisableConfirmationOAuthAuthorizeHandler)
              break
```

If needed, here is my full config: https://gitlab.esiea.fr/gauthier.heiss/esiea-jupyter-image/-/blob/main/JupyterHub.yaml

**I am pretty sure this config is not the perfect way to go and could be much simplier and secure.**
